### ISSUE TITLE
Create Method DownloadItem(Stream stream)

### ISSUE THREAD

**Issue by Kyrodan** [KoenZomers/OneDriveAPI#1]
The methods "DownloadItem" always save to a local file. In many situations it's better to download to a stream (Parameter stream) and handle subsequent operations from "outside" (the method caller side).

**Comment by Kyrodan** [comment]
Same for UploadItem.

**Comment by Kyrodan** [comment]
Maybe these overloaded "Shortcut-Methods" should be moved to to Extension Methods. Only basic methods should be left in the API-Class.

**Comment by KoenZomers** [comment]
Good point. I've added a new method which returns a stream with the OneDrive contents. For backwards compatibility and because I do believe that saving the contents to disk is core functionality, I will leave the current methods in place.
