### ISSUE TITLE
Autorization Scopes

### ISSUE THREAD

**Issue by Petje1972** [KoenZomers/OneDriveAPI#11]
Hi Koen,

At first it's a great API. Thanks for that!

It's not an issue but a question:
What is the best way to change the permission scopes?
I would like to use the Nuget compiled dll instead of changing source code after every improvement from your side.

I prefer not to have permissions for the complete Onedrive storage environment but only to my application appfolder.

Grtz Patrick

**Comment by KoenZomers** [comment]
Hi @Petje1972,

which of the types are you using? OneDriveConsumerApi, OneDriveForBusinessO365Api or OneDriveGraphApi?

**Comment by KoenZomers** [comment]
Closing as no further feedback has been received.
