### ISSUE TITLE
Upload file to group

### ISSUE THREAD

**Issue by Sejushi** [KoenZomers/OneDriveAPI#12]
Hi,
I'm trying to configure your library. This is really great!
I have one question. I use it with GraphApi authentication. And I have problem because i want to upload file from many user profiles to one public catalogue. The perfect scenario is: I have group (for example: https://xxx.sharepoint.com/sites/CRM/Shared%20Documents/Forms/AllItems.aspx) - how to upload file to this OneDrive location? By default I always send file to https://xxx-my.sharepoint.com/personal/xxx/Documents/) :(
Can you help me?

**Comment by KoenZomers** [comment]
Hi @Sejushi,

at this moment SharePoint sites are not yet supported to work with, only OneDrive Personal/Consumer and OneDrive for Business. You could share a folder on OneDrive for Business with your team and access that, that will work.

**Comment by Sejushi** [comment]
So, as I understand, the only one option is uploading file to folder:  https://(**my company**)-my.sharepoint.com/personal/(**my name and surname**)/Documents? I want to have no my personal data in the link when file is uploading by my colleague.
I use OneDriveGraphApi because I have OneDrive for Business license.

**Comment by KoenZomers** [comment]
That would be correct for this moment, yes.

**Comment by KoenZomers** [comment]
Closing as topic seems to have been discussed.
