### ISSUE TITLE
Demo application consumer onedrive authorzation isn't working?

### ISSUE THREAD

**Issue by jonas-s-s-s** [KoenZomers/OneDriveAPI#14]
I don't know if i'm doing something wrong, but when i try to use the consumer onedrive option in the demo app it crashes when I click the "authorize" button and displays this error: ![screenshot_9](https://user-images.githubusercontent.com/13944761/45901389-068e1200-bde3-11e8-8677-34355d98348a.png)
 (sorry that my VS isn't in english)
I didn't modify anything in the demo application, the other 2 option work fine only the consumer onedrive which I want to use doesn't work.

**Comment by KoenZomers** [comment]
Even if you want to connect to a OneDrive Consumer drive, it is recommended to use the Graph API. The Graph API allows connecting to both OneDrive Consumer as well as OneDrive for Business.

The error message indicates your app.config does not have an AppSetting for either of those values which you are using in the line when the error occurs. Check your app.config and ensure both of these exist.

**Comment by jonas-s-s-s** [comment]
> 
> 
> Even if you want to connect to a OneDrive Consumer drive, it is recommended to use the Graph API. The Graph API allows connecting to both OneDrive Consumer as well as OneDrive for Business.
> 
> The error message indicates your app.config does not have an AppSetting for either of those values which you are using in the line when the error occurs. Check your app.config and ensure both of these exist.

Ok, thanks. I'll use the graph API then.

**Comment by KoenZomers** [comment]
Perfect. Feel free to open a new issue if you run into trouble using that.
