### ISSUE TITLE
How to get driveitem from public folder or file?

### ISSUE THREAD

**Issue by Pilzinsel64** [KoenZomers/OneDriveAPI#16]
Hello!

This isn't realy a issue, but I realy don't know how to get a DriveItem from a public file like [this](https://1drv.ms/t/s!ArmiiThou14CinQhcXllCWBKvfS6). Or, how can I get a DriveItem from a public folder?

Thanks

Pilzinsel64

**Comment by Pilzinsel64** [comment]
Hello again!

Now it is an issue.
I tried to get the direct download like: https://onedrive.live.com/download?cid=025EBB683889A2B9&resid=25EBB683889A2B9!1396&authkey=AJxFQ8726d8On94
It works, but when I call OneDriveGraphApi.GetItemFromDriveById("25EBB683889A2B9%211396", "25EBB683889A2B9") I get this exception. Probably because it needs my authkey (AJxFQ8726d8On94) for this file, but there is no way to do that.

System.NullReferenceException
  HResult=0x80004003
  Nachricht = Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Quelle = KoenZomers.OneDrive.Api
  Stapelüberwachung:
   bei KoenZomers.OneDrive.Api.OneDriveApi.<SendMessageReturnHttpResponse>d__134.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KoenZomers.OneDrive.Api.OneDriveApi.<SendMessageReturnString>d__132.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KoenZomers.OneDrive.Api.OneDriveApi.<SendMessageReturnOneDriveItem>d__131`1.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KoenZomers.OneDrive.Api.OneDriveApi.<GetData>d__125`1.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei KoenZomers.OneDrive.Api.OneDriveApi.<GetItemFromDriveById>d__73.MoveNext()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei WindowsApp1.Form1.VB$StateMachine_8_LetsGo.MoveNext() in C:\Users\Pascal2\source\repos\WinConTests\WinConTests\Form1.vb: Zeile39

**Comment by KoenZomers** [comment]
The API is not designed to work with anonymous sharing links other than creating them. Why would you want to revert it to a DriveItem?

**Comment by Pilzinsel64** [comment]
I want to download files (e.g. for updater) in my tool and I don't want to put my encrypted account informations in this tool just do download shared files.

However, I've found a workaround by modifying the links for embeding files to be (direct) download links. Then I can download them via System.Net.WebRequest.

Embedded link:
https://onedrive.live.com/embed?cid=025EBB683889A2B9&resid=25EBB683889A2B9%211469&authkey=ALgRKMKtYWAC0cU

Download Link: -> Change "embed" to "download"
https://onedrive.live.com/download?cid=025EBB683889A2B9&resid=25EBB683889A2B9%211469&authkey=ALgRKMKtYWAC0cU

A feature to do this in your api still would be nice.

**Comment by KoenZomers** [comment]
So if I understand you correctly, you would like to see support added in the API to perform this operation:

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online

Which effectively would return you the embed link which you can transform into a download link.

Correct?

**Comment by KoenZomers** [comment]
Closing due to no response received.
