### ISSUE TITLE
Exception when call GetAccessToken()

### ISSUE THREAD

**Issue by pks888** [KoenZomers/OneDriveAPI#19]
Im using it  on xamarin.forms
```csharp

var uri = onedriveAPI.GetAuthenticationUri();
            browser.Source = uri;
            browser.Navigated += async (ss, ee) =>
            {
                Debug.WriteLine(ee.Url);

                // Get the currently displayed URL and show it in the textbox
                var url = ee.Url.ToString();

                // Check if the current URL contains the authorization token
                var authorizationCodeTxt = onedriveAPI.GetAuthorizationTokenFromUrl(ee.Url.ToString());

                // Verify if an authorization token was successfully extracted
                if (!string.IsNullOrEmpty(authorizationCodeTxt))
                {
                    //onedriveAPI. = authorizationCodeTxt;
                    // Get an access token based on the authorization token that we now have
                    var tok = await onedriveAPI.GetAccessToken();
                    if (onedriveAPI.AccessToken != null)
                    {
                        // Show the access token information in the textboxes```
}}}


```
the app can get the authorization token, but when i click the 'yes' button on the brower to enable the access, and then the app throw  an exception： Operation is not valid due to the current state of the object.

![屏幕快照 2019-05-06 下午12 51 42](https://user-images.githubusercontent.com/3284852/57207145-dd329700-6ffd-11e9-85d3-8d9ccc85c465.png)

**Comment by KoenZomers** [comment]
Try running Fiddler while you're making the call and look at the network traffic that gets generated. This likely already shows some abnormalities.

**Comment by KoenZomers** [comment]
Closing due to no response received.

**Comment by stoee** [comment]
![MDrWYZFhfPYuiJunjIYw9DveIKk cnt](https://user-images.githubusercontent.com/43819633/72308379-6a62db00-36b7-11ea-9fc2-7e10991402e4.jpg)

Exception when call GetAccessToken()

DEMO

**Comment by stoee** [comment]
DemoApplication. 

Failed to retrieve OneDrive access token. Additional information: AADSTS70002: The provided request must include a 'client_secret' input parameter.
![image](https://user-images.githubusercontent.com/43819633/72397139-e1f93e80-3779-11ea-94af-cb9fb23e1fa4.png)
![image](https://user-images.githubusercontent.com/43819633/72397146-e887b600-3779-11ea-981d-794595669529.png)

{"error":"invalid_client","error_description":"AADSTS70002: The provided request must include a 'client_secret' input parameter.\r\nTrace ID: 7b409a52-de5e-4c38-b76f-7c13ebd16a01\r\nCorrelation ID: 5f5bc486-b01e-49d6-b373-4bcebce3c213\r\nTimestamp: 2020-01-14 02:43:51Z","error_codes":[70002],"timestamp":"2020-01-14 02:43:51Z","trace_id":"7b409a52-de5e-4c38-b76f-7c13ebd16a01","correlation_id":"5f5bc486-b01e-49d6-b373-4bcebce3c213","error_uri":"https://login.microsoftonline.com/error?code=70002"}

**Comment by KoenZomers** [comment]
Which ClientID are you using to make the requests? Your own or the one in the code already? 

If your own, ensure you have "Treat application as public client" set to Yes in your Azure Active Directory App Registration under the Authentication section:
![image](https://user-images.githubusercontent.com/5940670/85392878-6ed7cd80-b54c-11ea-858b-be7774b8742f.png)

**Comment by KoenZomers** [comment]
Closing as no further response received.
