### ISSUE TITLE
Is there a way to use it in console app?

### ISSUE THREAD

**Issue by dzb87** [KoenZomers/OneDriveAPI#22]
Hey,
is there a way to use the library in console application?
I mean without logging in browser and with no GUI at all.

Regards

**Comment by KoenZomers** [comment]
Yes, that will be possible. You would need a refresh token to authenticate and then use
```C# 
oneDrive.AuthenticateUsingRefreshToken("yourrefreshtoken");
```
You could use the demo tool included in this code base to log in interactively once and get the refresh token from the fields at the bottom of the demo tool.

**Comment by KoenZomers** [comment]
Closing as no further feedback received
