### ISSUE TITLE
Can the new account still use onedrive personal API?

### ISSUE THREAD

**Issue by bbhxwl** [KoenZomers/OneDriveAPI#25]
Can the new account still use onedrive personal API?

I didn't succeed. I have ClientID and clientsecret

**Comment by bbhxwl** [comment]
？？？？

**Comment by KoenZomers** [comment]
Please be clearer in what you're trying to achieve. What's a "new account"?

**Comment by KoenZomers** [comment]
Closing issue as no further feedback has been received
