### ISSUE TITLE
I don't know why. Please take a look at it for me.

### ISSUE THREAD

**Issue by bbhxwl** [KoenZomers/OneDriveAPI#27]
I don't know why. Please take a look at it for me.
I can get root, which is the same as your demo, but I upload it, why fail, and your demo is OK?
{"error":{"code":"invalidRequest","message":"Item does not match expected type"}}

  static void Main(string[] args)
        {

           var t= Task.Run(async()=> {

                oneDrive = new OneDriveConsumerApi("*****", "*******");
                oneDrive.AuthenticationRedirectUrl = "******";
                string url = "http://*****.com/?code=M.R3_BAY.d88******";
                string msg = oneDrive.GetAuthorizationTokenFromUrl(url);
                 await oneDrive.GetAccessToken();
 
               while (true)
                {
                   try
                   {
                       string path = Console.ReadLine();
                       var root = await oneDrive.GetDriveRoot();
                          var f=    await oneDrive.UpdateFileViaSimpleUpload(new FileInfo(path),root);
                      // var f = await oneDrive.UpdateFile(path,new KoenZomers.OneDrive.Api.Entities.OneDriveItem() {  });
                       Console.WriteLine(f.OriginalJson);
                   }
                   catch (Exception ex)
                   {
                       Console.WriteLine(ex.Message);
                        
                   }
                   
                }

               
            });
            t.Wait();
    
        }

**Comment by bbhxwl** [comment]
Nuget prompt error is：{"error":{"code":"invalidRequest","message":"Item does not match expected type"}}

I refer to the API of your project, and the error is: {error ': {code': "invalidrequest", "message": "objecthandle is invalid", "innererror": {code ":" invalidresourceid "}}}

**Comment by bbhxwl** [comment]
I wrote upload as updatefile.. I got it! thank you. I manually get the URL of getauthorizationtokenfromurl myself. If my program is closed, the URL will be expired and can only be obtained once. Is there any way to recycle it?

**Comment by KoenZomers** [comment]
See https://github.com/KoenZomers/OneDriveAPI/issues/26
