### ISSUE TITLE
How to get multi page data?

### ISSUE THREAD

**Issue by bbhxwl** [KoenZomers/OneDriveAPI#28]
How to get multi page data?

await oneDrive.GetChildrenByPath("抖音");

This folder has 100000 data, but I can only get more than 100. How can I get the next page? If you use GetAllChildrenByPath, it will be very slow.

**Comment by bbhxwl** [comment]
I have updated onedrive, which supports China Century Internet, but I will not use your page. Ask for advice.

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/99879676-45c97f00-2c49-11eb-8917-793ec5680f63.png)
This folder has 70000 files. There's no way to get it.

**Comment by bbhxwl** [comment]
@KoenZomers

**Comment by KoenZomers** [comment]
Hi @bbhxwl. You're right, this wasn't possible yet unless you would go for retrieving all the results. I've added a method in the version I just released to deal with this and allow for retrieving the baches one by one yourself:

- Added ```public virtual async Task<OneDriveItemCollection> GetNextChildrenByPath(string skipTokenUrl)``` which allows file requests from using i.e. ```public virtual async Task<OneDriveItemCollection> GetChildrenByPath(string path)``` on a large folder containing more than 100 files to retrieve the next batch of files. If your intend is to get all the results, use ```public virtual async Task<OneDriveItem[]> GetAllChildrenByPath(string path)``` instead. [Issue 28](https://github.com/KoenZomers/OneDriveAPI/issues/28)

A sample of how to use it has been included in the Demo application. Here you can see how I pulled it off:
https://github.com/KoenZomers/OneDriveAPI/blob/fe1c89dde9937f4e1b7251390edf0ba2fcf290eb/Demo/MainForm.cs#L272

Let me know in case you have further questions.

**Comment by KoenZomers** [comment]
Closing it as no feedback received. Feel free to reopen in case it doesn't work for you.
