### ISSUE TITLE
[BUG] Brief description

### ISSUE THREAD

**Issue by azmilassoued** [KoenZomers/OneDriveAPI#30]
i'm getting token error  : KoenZomers.OneDrive.Api.Exceptions.TokenRetrievalFailedException : 'Failed to retrieve OneDrive access token. Additional information: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '862d394a-115d-44f2-a578-02cc29028ec6'.
Trace ID: 743a6d20-ba84-4c5b-80ee-7d480c66a400
Correlation ID: 729fbe5d-8599-4ccd-9409-e1e8781a9695
Timestamp: 2021-01-27 13:35:39Z'
could you help me to find a solution, i need it so much 

   

![image](https://user-images.githubusercontent.com/78089226/105999182-b065c380-60ad-11eb-8076-6a545f60365b.png)

**Comment by KoenZomers** [comment]
Looks like you're trying to use it with your own Azure Active Directory App registration under the client id 862d394a-115d-44f2-a578-02cc29028ec6, correct? Ensure you have added the following RedirectURI to your App Registation in your Azure Active Directory:

```https://login.microsoftonline.com/common/oauth2/nativeclient```

![image](https://user-images.githubusercontent.com/5940670/106531713-0e037100-64ef-11eb-8852-708a23e47860.png)

Or alternatively ensure that on the OneDrive instance you set the ```AuthenticationRedirectUrl``` property to match with whatever Redirect URI you want to use and ensure that the same URI is in your Azure Active Directory application registration.

![image](https://user-images.githubusercontent.com/5940670/106531820-3f7c3c80-64ef-11eb-9816-e9040f985312.png)

**Comment by azmilassoued** [comment]
Thank you for your response, it works good

**Comment by KoenZomers** [comment]
Thanks for confirming!
