### ISSUE TITLE
Connection by default

### ISSUE THREAD

**Issue by RolaQH** [KoenZomers/OneDriveAPI#32]
Hello, I want to access the different functions of your api, but I want to connect by default, setting the credentials manually (by code). To achieve this, do you have to configure something additional in the AZURE platform or can the authentication be done manually without the need to be typing the credentials in the GUI?
I am developing an ASP.NET MVC 5 Web application.

Thanks.

**Comment by KoenZomers** [comment]
Hi @RolaQH, please read the last part of my post at:
https://github.com/KoenZomers/OneDriveAPI/issues/34#issuecomment-811021562

And let me know in case that does not answer your question.

**Comment by KoenZomers** [comment]
Closing as no further comments or feedback have been received.
