### ISSUE TITLE
[QUESTION] How to solve "AADSTS500113: No reply address is registered for the application"

### ISSUE THREAD

**Issue by averied** [KoenZomers/OneDriveAPI#33]
I'm trying to test the demo application. I have setup my app in Azure. I have put my app id in the App.config fle. So now from Visual Studio I run the demo app, and when I select Graph API and click authorize, I put my office 365 credentials, and after that, I get this error:

AADSTS500113: No reply address is registered for the application

**EDIT**

Sorry, this was fixed with the instructions provided in the README:

- Click on Add a platform followed by clicking on Mobile and desktop applications
- Select the two proposed options for https://login.microsoftonline.com/common/oauth2/nativeclient and https://login.live.com/oauth20_desktop.srf and click on Configure at the bottom_

**Comment by averied** [comment]
Sorry, this was solved

**Comment by KoenZomers** [comment]
Closing issue as it has been answered by the topic starter itself already
