### ISSUE TITLE
Can sharing an item be revoked?

### ISSUE THREAD

**Issue by paulvanbladel** [KoenZomers/OneDriveAPI#6]
Koen,
Very nice Api and corresponding demo app.
Just a quick question.
Can a previous share of a document be revoked?
Thanks a lot
cheers
paul.

**Comment by KoenZomers** [comment]
Hi @paulvanbladel. Thanks. Currently that's not possible, but the API behind it supports it I can see: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/permission_delete . I'll look into adding this to my API and will update this issue once done.

**Comment by paulvanbladel** [comment]
Hoi Koen,
Thank you so much for the prompt feedback. (Remember, we met a few years ago in Leuven? :) )

I was just wondering if the API is .net core compatible?

Take care
paul.

**Comment by KoenZomers** [comment]
Hi @paulvanbladel, you name sounds familiar to me indeed, but can't recall your face with the name to be honest. I see too many new faces every week I guess :) I haven't tried this API with .NET Core yet, so no idea if it would be compatible and if not, how much work it would cost to make it compatible.

**Comment by KoenZomers** [comment]
Hi @paulvanbladel, all methods to work with permissions amongst which revoking (sharing) permissions have been added to v2.0.2.0 of the API which is now available.

**Comment by paulvanbladel** [comment]
Cool. Thanks koen.
